var nutrients = {
	'energy': 								'208',
	'protein': 								'203',
	'fat': 									'204',
	'carbohydrate': 						'205',
	'fiber': 								'291',
	'sugar': 								'269',
	'Ca': 									'301',
	'Fe': 									'303',
	'Mg': 									'304',
	'P': 									'305',
	'K': 									'306',
	'Na': 									'307',
	'Zn': 									'309',
	'Cu': 									'312',
	'Mn': 									'315',
	'Se': 									'317',
	'F': 									'313',
	'v_a': 									'318',
	'v_b6': 								'415',
	'v_b12': 								'418',
	'v_c': 									'401',
	'v_d3': 								'326',
	'v_e': 									'323',
	'v_k': 									'430',
	'fatty_acids_total_saturated': 			'606',
	'fatty_acids_total_monounsaturated':		'645',
	'fatty_acids_total_polyunsaturated':		'646',
	'fatty_acids_total_trans': 				'605',
	'DPA': 									'631',
	'DHA': 									'621',
	'cholesterol': 							'601',
	'alcohol_ethyl': 						'221',
	'caffeine': 							'262'
};

var foodGroups = {
	'egg': 								'1',
	'spices_and_herbs': 				'2',
	'baby_foods': 						'3',
	'fats_and_oils': 					'4',
	'poultry': 							'5',
	'soups_sauces_and_gravies': 		'6',
	'sausages_and_luncheon_meats': 		'7',
	'breakfast_cereals': 				'8',
	'fruits_and_fruit_juices': 			'9',
	'pork': 							'10',
	'vegetables': 						'11',
	'nuts_and_seeds': 					'12',
	'beef': 							'13',
	'beverages': 						'14',
	'fish_and_shellfish': 				'15',
	'legumes': 							'16',
	'lamb_veal_and_game': 				'17',
	'baked_products': 					'18',
	'sweets': 							'19',
	'cereal_grains_and_pasta': 			'20',
	'fast_foods': 						'21',
	'meals_entrees_and_side_dishes':	'22'
};

module.exports = {
	nutrients: nutrients,
	foodGroups: foodGroups,
	apiKey: 'PYza6j5W6M2Cq863svJxiz1p8qV2qoGCgGf0SyH4'
};